name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'config/**' # Only trigger if changes happen in the 'config' folder
      - '!.github/workflows/**' # Exclude changes in the '.github/workflows' folder
  pull_request:
    paths:
      - 'config/**'
      - '!.github/workflows/**'
    branches:
      - main
  workflow_dispatch: # Allow for manual workflow dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/checkout@v4
        with:
          repository: moergo-sc/zmk
          ref: main
          path: src
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v14
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true

      # Setup python to run scripts
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install the dependencies
      # - name: Cache Python dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/scripts/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-
      # - name: Install Python dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r scripts/requirements.txt
      
      # Updates the max combo of the files
      - name: Run Python script
        run: python scripts/update-max-combo.py config/glove80.keymap config/glove80.conf

      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 glove80.uf2
      - name: Upload result
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: "glove80-${{ github.sha }}.uf2" # Include commit hash in the artifact name
          path: glove80.uf2

