name: Build

on:
  push:
    paths:
      - 'config/**' # Only trigger if changes happen in the 'config' folder
      - '!.github/workflows/**' # Exclude changes in the '.github/workflows' folder
  pull_request:
    paths:
      - 'config/**'
      - '!.github/workflows/**'
  workflow_dispatch: # Allow for manual workflow dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/checkout@v4
        with:
          repository: moergo-sc/zmk
          ref: main
          path: src
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v14
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 glove80.uf2
      - name: Upload result
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: glove80-$GITHUB_SHA.uf2 # Include commit hash in the artifact name
          path: glove80.uf2
